[package]
name = "egui-bind"
version = "0.2.0"
edition = "2021"
description = "Library for showing keybinds"
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/egui-bind"

[dependencies]
egui = "0.19"

[dev-dependencies]
eframe = "0.19"
